#!/bin/bash

#PBS -N gr4j_cnn
#PBS -l select=1:ncpus=8:mem=16gb 
#PBS -l walltime=12:00:00 
#PBS -M arpit.kapoor@unsw.edu.au 
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5370003/logs/train_hybrid_gr4j_cnn.log

cd $PBS_O_WORKDIR

/srv/scratch/z5370003/miniconda3/envs/hydroml/bin/python train_hybrid_gr4j_cnn.py --data-dir ../data/camels/aus --sub-dir no-scale-seq --run-dir ../results/deepgr4j_cnn_qin --gr4j-run-dir ../results/gr4j --dropout 0.1 --lr 0.001 --n-filters 8 8 6 --window-size 7 --q-in
